WITH FILAS AS (SELECT  X, Y, 
    ROW_NUMBER() OVER (ORDER BY X asc) AS fila
    FROM FUNCTIONS F
)
SELECT F1.X, F1.Y FROM FILAS F1
WHERE (F1.X,F1.Y) IN 
(   SELECT F2.Y, F2.X
    FROM FILAS F2 
    WHERE F1.X = F2.Y AND F2.X = F1.Y 
    AND  F1.fila < F2.fila
    ORDER BY  F2.X ASC  )
AND F1.X <= F1.Y
ORDER BY F1.X ASC
